# Generated by Django 5.0.2 on 2024-02-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_categoria_created_at_categoria_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False, help_text='0=default , 1=oferta', null=True),
        ),
    ]
