# Generated by Django 5.0.2 on 2024-03-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_en_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False, help_text='0=no oferta , 1=oferta', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='0=Inactivo , 1=Activo'),
        ),
    ]
