# Generated by Django 5.0.2 on 2024-03-01 14:18

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_producto_en_oferta_alter_producto_esta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
