# Generated by Django 5.0.2 on 2024-03-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_categoria_slug_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cod_barras',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
